version: "3.3"
services:
  api-gateway:
    build:
      context: ApiGateway/
      dockerfile: ./ApiGateway/Dockerfile
    environment:
      BASKET_SERVICE: "http://basket_service:3000/api/"
      ORDER_SERVICE: "http://order_service:8080/api/"
      PRODUCT_SERVICE: "http://product-catalog:8080/api/"
    ports:
      - "8080:80"
    depends_on:
      - product-catalog
      - basket_service
      - order_service
  product-catalog:
    build: ProductCatalog/
    environment:
      MONGODBATLASURI: ${MONGODBATLASURI}
    ports:
      - "8085:8080"
  basket_service:
    build: basket-microservice/
    environment:
      REDIS_URL: "redis"
      RESET_REDIS_PW: ${RESET_REDIS_PW}
    ports:
      - "8086:3000"
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  order_service:
    build: OrderService/
    ports:
      - "8075:8080"
    environment:
      DB_URL: "jdbc:postgresql://order_db:5432/postgres"
      DB_USERNAME: "postgres"
      DB_PW: "postgres"
    depends_on:
      - order_db
  order_db:
    image: "postgres:alpine"
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"

